- name: OCaml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install OCaml
      ansible.builtin.package:
        name:
          - ocaml
          - ocaml-dune
          - ocaml-opam
        state: present

    - name: Initialize opam
      ansible.builtin.command: opam init --disable-sandboxing --shell-setup --yes
      args:
        creates: /root/.opam
      environment:
        HOME: /root

    - name: Install utop via opam
      ansible.builtin.command: opam install utop --yes
      environment:
        HOME: /root
        OPAMROOT: /root/.opam
        OPAMSWITCH: default
