- name: XFCE + LightDM
  hosts: localhost
  gather_facts: false
  become: true
  become_method: doas

  vars:
    PACKAGES: []
    DESKTOP_USER: "hypha"
    DESKTOP_PASSWORD_HASH: "$6$Rxmu00iHFfy.vOlb$gX4kyLiXFoeob/.fA0EesOm1Cg4Dkcd0i/0dZZqIrW0P.Jnki9rGp4brp73zJvrV1mc42sB5IlUiY/LGcBh5r0"
    DESKTOP_PACKAGES:
      - ca_root_nss
      - dbus
      - ffmpegthumbnailer
      - file-roller
      - firefox
      - gvfs
      - lightdm
      - lightdm-gtk-greeter
      - mousepad
      - nano
      - networkmgr
      - pavucontrol
      - polkit
      - pulseaudio
      - shared-mime-info
      - thunar-archive-plugin
      - xdg-utils
      - xfce
      - xfce4-goodies
      - xfce4-terminal
      - xfce4-tumbler
      - xorg
    X_RESOLUTION: "1024x768"

  tasks:
    - name: Update pkg metadata
      ansible.builtin.command: pkg update -f
      changed_when: false

    - name: Install desktop packages
      ansible.builtin.package:
        name: "{{ DESKTOP_PACKAGES }}"
        state: present

    - name: Install extra packages
      ansible.builtin.package:
        name: "{{ PACKAGES }}"
        state: present
      when: PACKAGES | length > 0

    - name: Set EFI framebuffer max resolution (ramfb/scfb)
      ansible.builtin.lineinfile:
        path: /boot/loader.conf
        create: yes
        regexp: '^efi_max_resolution='
        line: 'efi_max_resolution="{{ X_RESOLUTION }}"'

    - name: Ensure VT console is used
      ansible.builtin.lineinfile:
        path: /boot/loader.conf
        create: yes
        regexp: '^kern\.vty='
        line: 'kern.vty=vt'

    - name: Enable required services
      ansible.builtin.command: "{{ item }}"
      loop:
        - sysrc dbus_enable=YES
        - sysrc lightdm_enable=YES
        - sysrc moused_enable=YES
      changed_when: false

    - name: Start services now
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - dbus
        - moused
        - lightdm

    - name: Ensure desktop user exists
      ansible.builtin.user:
        name: "{{ DESKTOP_USER }}"
        groups: "wheel,video"
        append: yes
        shell: /bin/tcsh
        create_home: yes
        password: "{{ DESKTOP_PASSWORD_HASH }}"
        update_password: on_create
        state: present
