- name: Nginx
  hosts: localhost
  gather_facts: false

  vars:
    NGINX_LISTEN_PORT: 80
    NGINX_SERVER_NAME: "_"
    NGINX_ROOT: "/usr/local/www/nginx"
    NGINX_ACCESS_LOG: "/var/log/nginx/access.log"
    NGINX_ERROR_LOG: "/var/log/nginx/error.log"

    NGINX_CONF_DIR: "/usr/local/etc/nginx"
    NGINX_CONF_FILE: "nginx.conf"
    NGINX_CONF_PATH: "{{ NGINX_CONF_DIR }}/{{ NGINX_CONF_FILE }}"

  tasks:
    - name: Install nginx
      ansible.builtin.command: pkg install -y nginx

    - name: Enable nginx
      ansible.builtin.command: sysrc nginx_enable=YES

    - name: Create web root
      ansible.builtin.file:
        path: "{{ NGINX_ROOT }}"
        state: directory
        mode: "0755"

    - name: Ensure log directory exists
      ansible.builtin.file:
        path: /var/log/nginx
        state: directory
        mode: "0755"

    - name: Ensure nginx config directory exists
      ansible.builtin.file:
        path: "{{ NGINX_CONF_DIR }}"
        state: directory
        mode: "0755"

    - name: Install nginx.conf from template
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "{{ NGINX_CONF_PATH }}"
        mode: "0644"
      notify: reload nginx

    - name: Install default index page from template
      ansible.builtin.template:
        src: index.html.j2
        dest: "{{ NGINX_ROOT }}/index.html"
        mode: "0644"
      notify: reload nginx

    - name: Test nginx config
      ansible.builtin.command: nginx -t -c {{ NGINX_CONF_PATH }}
      register: nginx_test
      changed_when: false

    - name: Ensure nginx is running
      ansible.builtin.command: service nginx start
      register: nginx_start
      failed_when: >
        nginx_start.rc != 0 and
        'already running' not in (nginx_start.stderr | default(''))

  handlers:
    - name: reload nginx
      ansible.builtin.command: service nginx reload
